# Generated by Django 5.0 on 2024-04-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0002_categoria_entrenamiento_codigodescuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='porcentajeDescuento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
