# Generated by Django 5.0 on 2024-04-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0003_entrenamiento_porcentajedescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='tipoDePago',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
