# Generated by Django 5.0 on 2024-04-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0004_entrenamiento_tipodepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
