# Generated by Django 4.2.7 on 2023-11-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pala',
            fields=[
                ('palaID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='palas')),
                ('marca', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('precio_rebaja', models.FloatField()),
                ('temporada', models.IntegerField()),
                ('material_marco', models.CharField(max_length=255)),
                ('material_plano', models.CharField(max_length=255)),
                ('material_goma', models.CharField(max_length=255)),
                ('tacto', models.CharField(blank=True, choices=[('Blando', 'Blando'), ('Medio-Duro', 'Medio-Duro'), ('Duro', 'Duro'), ('Medio-Blando', 'Medio-Blando'), ('Medio', 'Medio')], max_length=20, null=True)),
                ('forma', models.CharField(choices=[('diamante', 'Diamante'), ('redonda', 'Redonda'), ('hibrida', 'Híbrida')], max_length=10)),
                ('peso', models.CharField(max_length=20)),
                ('total_padelzoom', models.FloatField()),
                ('potencia', models.FloatField()),
                ('control', models.FloatField()),
                ('salida_bola', models.FloatField()),
                ('manejabilidad', models.FloatField()),
                ('punto_dulce', models.FloatField()),
                ('fondo_de_pista', models.FloatField()),
                ('volea', models.FloatField()),
                ('bajada_de_pared', models.FloatField()),
                ('bandeja', models.FloatField()),
                ('remate', models.FloatField()),
                ('defensa', models.FloatField()),
                ('ataque', models.FloatField()),
                ('puntuacion_total', models.FloatField()),
                ('balance', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_promocional', models.CharField(blank=True, max_length=50, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioPala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('url', models.URLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparador.pala')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparador.tienda')),
            ],
        ),
    ]
