# Generated by Django 4.2.7 on 2023-11-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pala',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='palas_images/')),
                ('marca', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('precio_rebaja', models.FloatField()),
                ('temporada', models.IntegerField()),
                ('material_marco', models.CharField(max_length=255)),
                ('material_plano', models.CharField(max_length=255)),
                ('material_goma', models.CharField(max_length=255)),
                ('tacto', models.TextField()),
                ('forma', models.CharField(choices=[('diamante', 'Diamante'), ('redonda', 'Redonda'), ('hibrida', 'Híbrida')], max_length=10)),
                ('peso', models.CharField(max_length=20)),
                ('total_padelzoom', models.FloatField()),
                ('potencia', models.FloatField()),
                ('control', models.FloatField()),
                ('salida_bola', models.FloatField()),
                ('manejabilidad', models.FloatField()),
                ('punto_dulce', models.FloatField()),
                ('fondo_de_pista', models.FloatField()),
                ('volea', models.FloatField()),
                ('bajada_de_pared', models.FloatField()),
                ('bandeja', models.FloatField()),
                ('remate', models.FloatField()),
                ('defensa', models.FloatField()),
                ('ataque', models.FloatField()),
                ('puntuacion_total', models.FloatField()),
                ('balance', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=10)),
            ],
        ),
    ]
