# Generated by Django 4.2.7 on 2023-11-16 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalaBuscada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparador.pala')),
            ],
        ),
    ]
