# Generated by Django 5.0 on 2023-12-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0002_palabuscada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pala',
            name='nivel',
            field=models.CharField(blank=True, choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='NINGUNO', max_length=12),
        ),
        migrations.AlterField(
            model_name='pala',
            name='balance',
            field=models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=12),
        ),
    ]
