# Generated by Django 5.0 on 2023-12-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0003_pala_nivel_alter_pala_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciopala',
            name='url',
        ),
        migrations.AddField(
            model_name='tienda',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
