# Generated by Django 5.0 on 2023-12-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0004_remove_preciopala_url_tienda_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas'),
        ),
    ]
