# Generated by Django 4.2.7 on 2023-11-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0004_alter_pala_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pala',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='palas'),
        ),
        migrations.AlterField(
            model_name='pala',
            name='tacto',
            field=models.CharField(blank=True, choices=[('Blando', 'Blando'), ('Medio-Duro', 'Medio-Duro'), ('Duro', 'Duro'), ('Medio-Blando', 'Medio-Blando'), ('Medio', 'Medio')], max_length=20, null=True),
        ),
    ]
