# Generated by Django 5.0 on 2024-01-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0005_tienda_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pala',
            name='ataque',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='bajada_de_pared',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='bandeja',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='control',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='defensa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='fondo_de_pista',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='manejabilidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='potencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='precio_rebaja',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='punto_dulce',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='puntuacion_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='remate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='salida_bola',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='total_padelzoom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pala',
            name='volea',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
