# Generated by Django 4.2.7 on 2023-11-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0005_alter_pala_imagen_alter_pala_tacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_promocional', models.CharField(blank=True, max_length=50, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioPala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('url', models.URLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparador.pala')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparador.tienda')),
            ],
        ),
    ]
