# Generated by Django 5.0 on 2024-01-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0006_alter_pala_ataque_alter_pala_bajada_de_pared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pala',
            name='forma',
            field=models.CharField(choices=[('Diamante', 'Diamante'), ('Redonda', 'Redonda'), ('Hibrida', 'Híbrida')], max_length=10),
        ),
    ]
