# Generated by Django 5.0 on 2024-05-26 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comparador', '0007_alter_pala_forma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versus',
            fields=[
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('palas', models.ManyToManyField(to='comparador.pala')),
            ],
        ),
    ]
