# Generated by Django 5.0 on 2024-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0009_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='palas',
            field=models.ManyToManyField(related_name='favoritos', to='comparador.pala'),
        ),
    ]
