# Generated by Django 5.0 on 2024-05-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0010_alter_favorito_palas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoPublicitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la campaña publiciaria, por ejemplo: "Black Friday 2021"', max_length=255)),
                ('inicio_1', models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publicidad')),
                ('inicio_2', models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publicidad')),
                ('inicio_3', models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publicidad')),
                ('filtros_1', models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publicidad')),
                ('filtros_2', models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publicidad')),
                ('activo', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
