# Generated by Django 5.0 on 2024-05-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0013_alter_contenidopublicitario_filtros_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContenidoPublicitario',
        ),
        migrations.AddField(
            model_name='pala',
            name='total_favoritos',
            field=models.IntegerField(default=0),
        ),
    ]
