# Generated by Django 5.0 on 2024-05-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0014_delete_contenidopublicitario_pala_total_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='palas',
            field=models.ManyToManyField(blank=True, null=True, related_name='favoritos', to='comparador.pala'),
        ),
    ]
