# Generated by Django 5.0 on 2024-03-23 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionblog',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
