# Generated by Django 5.0 on 2024-04-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_seccionblog_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='portada',
            field=models.ImageField(default='test.png', upload_to='blog/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VisitaBlog',
        ),
    ]
