# Generated by Django 5.0 on 2024-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_loguin_requerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
