# Generated by Django 5.0 on 2024-04-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_categoria_blogpost_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
    ]
