# Generated by Django 5.0 on 2024-06-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='fotoAutor',
            field=models.ImageField(blank=True, null=True, upload_to='blog/autor/'),
        ),
    ]
