# Generated by Django 4.2.1 on 2023-06-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_categoria_producto_equ_plan_subcategoria_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ficha_producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='ficha_producto',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='ficha_producto',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='ficha',
            name='is_price_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ficha',
            name='offer_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='regular_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ficha_producto',
            name='allows_financing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ficha_producto',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ficha_producto',
            name='is_auctioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ficha_producto',
            name='takes_offers',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoria_producto',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ficha_producto',
            name='image2',
            field=models.FileField(blank=True, upload_to='images/fichas/products/'),
        ),
        migrations.AlterField(
            model_name='ficha_producto',
            name='image3',
            field=models.FileField(blank=True, upload_to='images/fichas/products/'),
        ),
        migrations.AlterField(
            model_name='ficha_producto',
            name='image4',
            field=models.FileField(blank=True, upload_to='images/fichas/products/'),
        ),
        migrations.AlterField(
            model_name='ficha_producto',
            name='image5',
            field=models.FileField(blank=True, upload_to='images/fichas/products/'),
        ),
        migrations.AlterField(
            model_name='ficha_producto',
            name='main_image',
            field=models.FileField(upload_to='images/fichas/products/'),
        ),
        migrations.CreateModel(
            name='Subcategoria_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categoria_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.FileField(upload_to='images/fichas/services/')),
                ('image2', models.FileField(blank=True, upload_to='images/fichas/services/')),
                ('image3', models.FileField(blank=True, upload_to='images/fichas/services/')),
                ('schedule', models.TextField()),
                ('takes_offers', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categoria_servicio')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subcategoria_servicio')),
            ],
        ),
    ]
