# Generated by Django 4.2.1 on 2023-06-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_categoria_servicio_marca_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equ_plan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='ficha_producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ficha_servicio',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ficha_servicio',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Marca_Producto',
        ),
        migrations.RemoveField(
            model_name='subcategoria_producto',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategoria_servicio',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Categoria_Producto',
        ),
        migrations.DeleteModel(
            name='Categoria_Servicio',
        ),
        migrations.DeleteModel(
            name='Equ_Plan',
        ),
        migrations.DeleteModel(
            name='Ficha',
        ),
        migrations.DeleteModel(
            name='Ficha_Producto',
        ),
        migrations.DeleteModel(
            name='Ficha_Servicio',
        ),
        migrations.DeleteModel(
            name='Subcategoria_Producto',
        ),
        migrations.DeleteModel(
            name='Subcategoria_Servicio',
        ),
    ]
