# Generated by Django 5.0 on 2023-12-09 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrella',
            name='valoracion',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
