# Generated by Django 5.0 on 2023-12-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valoraciones', '0002_estrella_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(default='Hola'),
            preserve_default=False,
        ),
    ]
