# Generated by Django 5.0 on 2024-05-27 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerspubli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidopublicitario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contenidopublicitario',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenidopublicitario',
            name='nombre',
            field=models.CharField(default='Test', help_text='Nombre de la campaña publiciaria, por ejemplo: "Black Friday 2021"', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenidopublicitario',
            name='filtros_1',
            field=models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publicidad'),
        ),
        migrations.AlterField(
            model_name='contenidopublicitario',
            name='filtros_2',
            field=models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publicidad'),
        ),
        migrations.AlterField(
            model_name='contenidopublicitario',
            name='inicio_1',
            field=models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publicidad'),
        ),
        migrations.AlterField(
            model_name='contenidopublicitario',
            name='inicio_2',
            field=models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publicidad'),
        ),
        migrations.AlterField(
            model_name='contenidopublicitario',
            name='inicio_3',
            field=models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publicidad'),
        ),
    ]
