# Generated by Django 5.0 on 2024-05-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerspubli', '0002_contenidopublicitario_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidopublicitario',
            name='filtros_1',
            field=models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publi'),
        ),
        migrations.AlterField(
            model_name='contenidopublicitario',
            name='filtros_2',
            field=models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publi'),
        ),
        migrations.AlterField(
            model_name='contenidopublicitario',
            name='inicio_1',
            field=models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publi'),
        ),
        migrations.AlterField(
            model_name='contenidopublicitario',
            name='inicio_2',
            field=models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publi'),
        ),
        migrations.AlterField(
            model_name='contenidopublicitario',
            name='inicio_3',
            field=models.ImageField(blank=True, help_text='Tamaño recomendado: 1920x1080', null=True, upload_to='publi'),
        ),
    ]
