# Generated by Django 5.0 on 2024-06-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerspubli', '0003_alter_contenidopublicitario_filtros_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidopublicitario',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
