# Generated by Django 5.0 on 2024-06-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bannerspubli', '0004_contenidopublicitario_redirect_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenidopublicitario',
            old_name='redirect_url',
            new_name='url',
        ),
    ]
