# Generated by Django 5.0 on 2024-06-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerspubli', '0005_rename_redirect_url_contenidopublicitario_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidopublicitario',
            name='url',
        ),
        migrations.AddField(
            model_name='contenidopublicitario',
            name='filtros_1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenidopublicitario',
            name='filtros_2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenidopublicitario',
            name='inicio_1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenidopublicitario',
            name='inicio_2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenidopublicitario',
            name='inicio_3_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
